<?
namespace Modules;


class Ktr_121_02_40
{
    public $module_config = [
        "ob_BurnOn_1" => ["hex" => "0000", "dec" => 0.0, "type" => "bool", "access" => "R", "dicription" => "DO1 Запрос на розжиг горелки №1"],
        "ob_BurnOn_2" => ["hex" => "0001", "dec" => 0.1, "type" => "bool", "access" => "R", "dicription" => "DO2 Запрос на розжиг горелки №2"],
        "ob_BurnC_1s_1" => ["hex" => "0002", "dec" => 0.2, "type" => "bool", "access" => "R", "dicription" => "DO3 Первая (Вторая) ступень горелки №1 ИЛИ Сигнал 'Закрыть' сервопривод горелки №1"],
        "ob_BurnO_2s_1" => ["hex" => "0003", "dec" => 0.3, "type" => "bool", "access" => "R", "dicription" => "DO4 Вторая (Третья) ступень горелки №1 ИЛИ Сигнал 'Открыть' сервопривод горелки №1"],
        "ob_BurnC_1s_2" => ["hex" => "0004", "dec" => 0.4, "type" => "bool", "access" => "R", "dicription" => "DO5 Первая (Вторая) ступень горелки №2 ИЛИ Сигнал 'Закрыть' сервопривод горелки №2"],
        "ob_BurnO_2s_2" => ["hex" => "0005", "dec" => 0.5, "type" => "bool", "access" => "R", "dicription" => "DO6 Вторая (Третья) ступень горелки №2 ИЛИ Сигнал 'Открыть' сервопривод горелки №2"],
        "ob_AvGen" => ["hex" => "0007", "dec" => 0.7, "type" => "bool", "access" => "R", "dicription" => "DO8 Лампа Авария общая"],
        "ob_LedWork" => ["hex" => "0008", "dec" => 0.8, "type" => "bool", "access" => "R", "dicription" => "Светодиод 'Работа'"],
        "ob_LedAv" => ["hex" => "0009", "dec" => 0.9, "type" => "bool", "access" => "R", "dicription" => "Светодиод 'Авария'"],
        "ib_Burn_En_1" => ["hex" => "1000", "dec" => 256.0, "type" => "bool", "access" => "R", "dicription" => "DI1 Авария горелки (Разрешение работы) №1"],
        "ib_Burn_W_1" => ["hex" => "1001", "dec" => 256.1, "type" => "bool", "access" => "R", "dicription" => "DI2 Подтверждение работы горелки №1"],
        "ib_Burn_En_2" => ["hex" => "1002", "dec" => 256.2, "type" => "bool", "access" => "R", "dicription" => "DI3 Авария горелки (Разрешение работы) №2"],
        "ib_Burn_W_2" => ["hex" => "1003", "dec" => 256.3, "type" => "bool", "access" => "R", "dicription" => "DI4 Подтверждение работы горелки №2"],
        "ib_AvButton" => ["hex" => "1004", "dec" => 256.4, "type" => "bool", "access" => "R", "dicription" => "DI5 Кнопка Аварийный останов"],
        "ib_Start" => ["hex" => "1006", "dec" => 256.6, "type" => "bool", "access" => "R", "dicription" => "DI7 Кнопка Старт(Стоп)"],
        "ib_ResetAv" => ["hex" => "1007", "dec" => 256.7, "type" => "bool", "access" => "R", "dicription" => "DI8 Кнопка Сброс аварий"],
        "ib_AvFire" => ["hex" => "2100", "dec" => 528.0, "type" => "bool", "access" => "R", "dicription" => "DI1 Датчик пожара"],
        "ib_BreakIn" => ["hex" => "2101", "dec" => 528.1, "type" => "bool", "access" => "R", "dicription" => "DI2 Сигнал от охранной сигнализации"],
        "ib_Pf_LAL" => ["hex" => "2102", "dec" => 528.2, "type" => "bool", "access" => "R", "dicription" => "DI3 Давление газа мало (реле давления)"],
        "ib_Pf_HAL" => ["hex" => "2103", "dec" => 528.3, "type" => "bool", "access" => "R", "dicription" => "DI4 Давление газа велико (реле давления)"],
        "ib_AvCO" => ["hex" => "2104", "dec" => 528.4, "type" => "bool", "access" => "R", "dicription" => "DI5 Датчик загазованности помещения CO"],
        "ib_AvCH" => ["hex" => "2105", "dec" => 528.5, "type" => "bool", "access" => "R", "dicription" => "DI6 Датчик загазованности помещения CН"],
        "ib_Gas_LS" => ["hex" => "2106", "dec" => 528.6, "type" => "bool", "access" => "R", "dicription" => "DI7 Положение газового клапана"],
        "ob_AvFire" => ["hex" => "2108", "dec" => 528.8, "type" => "bool", "access" => "R", "dicription" => "DO1 Включить лампу «Пожар»"],
        "ob_AvBreakIn" => ["hex" => "2109", "dec" => 528.9, "type" => "bool", "access" => "R", "dicription" => "DO2 Включить лампу «Взлом»"],
        "ob_AvPf" => ["hex" => "210A", "dec" => 528.10, "type" => "bool", "access" => "R", "dicription" => "DO3 Включить лампу «Авария давления газа»"],
        "ob_AvPwd" => ["hex" => "210B", "dec" => 528.11, "type" => "bool", "access" => "R", "dicription" => "DO4 Включить лампу «Авария давления теплоносителя»"],
        "ob_AvCO" => ["hex" => "210C", "dec" => 528.12, "type" => "bool", "access" => "R", "dicription" => "DO5 Включить лампу «Загазованность CO»"],
        "ob_AvCH" => ["hex" => "210D", "dec" => 528.13, "type" => "bool", "access" => "R", "dicription" => "DO6 Включить лампу «Загазованность CH»"],
        "ib_Burn_Av_3" => ["hex" => "2120", "dec" => 530.0, "type" => "bool", "access" => "R", "dicription" => "DI1 Авария горелки (Разрешение работы) №3"],
        "ib_Burn_W_3" => ["hex" => "2121", "dec" => 530.1, "type" => "bool", "access" => "R", "dicription" => "DI2 Подтверждение работы горелки №3"],
        "ib_Burn_Av_4" => ["hex" => "2122", "dec" => 530.2, "type" => "bool", "access" => "R", "dicription" => "DI3 Авария горелки (Разрешение работы) №4"],
        "ib_Burn_W_4" => ["hex" => "2123", "dec" => 530.3, "type" => "bool", "access" => "R", "dicription" => "DI4 Подтверждение работы горелки №4"],
        "ob_BurnOn_3" => ["hex" => "2128", "dec" => 530.8, "type" => "bool", "access" => "R", "dicription" => "DO1 Запрос на розжиг горелки №3"],
        "ob_BurnOn_4" => ["hex" => "2129", "dec" => 530.9, "type" => "bool", "access" => "R", "dicription" => "DO2 Запрос на розжиг горелки №4"],
        "ob_BurnC_1s_3" => ["hex" => "212A", "dec" => 530.10, "type" => "bool", "access" => "R", "dicription" => "DO3 Первая (Вторая) ступень горелки №3 ИЛИ Сигнал 'Закрыть' сервопривод горелки №3"],
        "ob_BurnO_2s_3" => ["hex" => "212B", "dec" => 530.11, "type" => "bool", "access" => "R", "dicription" => "DO4 Вторая (Третья) ступень горелки №3 ИЛИ Сигнал 'Открыть' сервопривод горелки №3"],
        "ob_BurnC_1s_4" => ["hex" => "212C", "dec" => 530.12, "type" => "bool", "access" => "R", "dicription" => "DO5 Первая (Вторая) ступень горелки №4 ИЛИ  Сигнал 'Закрыть' сервопривод горелки №4"],
        "ob_BurnO_2s_4" => ["hex" => "212D", "dec" => 530.13, "type" => "bool", "access" => "R", "dicription" => "DO6 Вторая (Третья) ступень горелки №4 ИЛИ Сигнал 'Открыть' сервопривод горелки №4"],
        "mode_Bo_1" => ["hex" => "200", "dec" => 512, "type" => "word", "access" => "RW", "dicription" => "Статус котла №1"],
        "mode_Bo_2" => ["hex" => "201", "dec" => 513, "type" => "word", "access" => "RW", "dicription" => "Статус котла №2"],
        "mode_Bo_3" => ["hex" => "202", "dec" => 514, "type" => "word", "access" => "RW", "dicription" => "Статус котла №3"],
        "mode_Bo_4" => ["hex" => "203", "dec" => 515, "type" => "word", "access" => "RW", "dicription" => "Статус котла №4"],
        "ia_Twd" => ["hex" => "204", "dec" => 516, "type" => "real", "access" => "R", "dicription" => "AI1 Температура теплоносителя в общем подающем трубопроводе"],
        "ia_Pwd" => ["hex" => "208", "dec" => 520, "type" => "real", "access" => "R", "dicription" => "AI3 Давление теплоносителя в общем трубопроводе"],
        "ia_Tao" => ["hex" => "20А", "dec" => 522, "type" => "real", "access" => "R", "dicription" => "AI4 Температура наружного воздуха"],
        "oa_Burn_Pwr_1" => ["hex" => "20C", "dec" => 524, "type" => "word", "access" => "R", "dicription" => "Производительность котла № 1"],
        "oa_Burn_Pwr_2" => ["hex" => "20D", "dec" => 525, "type" => "word", "access" => "R", "dicription" => "Производительность котла № 2"],
        "oa_Burn_Pwr_3" => ["hex" => "20Е", "dec" => 526, "type" => "word", "access" => "R", "dicription" => "Производительность котла № 3"],
        "oa_Burn_Pwr_4" => ["hex" => "20F", "dec" => 527, "type" => "word", "access" => "R", "dicription" => "Производительность котла № 4"],
        "oa_BurnPwr" => ["hex" => "211", "dec" => 529, "type" => "word", "access" => "R", "dicription" => "Выходная мощность каскада котлов"],
        "cmd_1" => ["hex" => "214", "dec" => 532, "type" => "word", "access" => "W", "dicription" => "Командное слово 1"],
        "net_Start" => ["hex" => "2140", "dec" => 532.0, "type" => "bool", "access" => "W", "dicription" => "Перейти в режим Старт"],
        "net_ResetAv" => ["hex" => "2142", "dec" => 532.2, "type" => "bool", "access" => "W", "dicription" => "Сброс аварий"],
        "cmd_Pwd_On" => ["hex" => "2147", "dec" => 532.7, "type" => "bool", "access" => "W", "dicription" => "Включить контроль давления теплоносителя"],
        "cmd_AvCheck_On" => ["hex" => "2148", "dec" => 532.8, "type" => "bool", "access" => "W", "dicription" => "Включить контроль общекотельных аварий"],
        "cmd_2" => ["hex" => "215", "dec" => 533, "type" => "word", "access" => "W", "dicription" => "Командное слово 2"],
        "net_Stop" => ["hex" => "2150", "dec" => 533.0, "type" => "bool", "access" => "W", "dicription" => "Перейти в режим 'Стоп'"],
        "cmd_Pwd_Off" => ["hex" => "2157", "dec" => 533.7, "type" => "bool", "access" => "W", "dicription" => "Отключить контроль давления теплоносителя"],
        "cmd_AvCheck_Off" => ["hex" => "2158", "dec" => 533.8, "type" => "bool", "access" => "W", "dicription" => "Отключить контроль общекотельных аварий"],
        "code_Sys" => ["hex" => "216", "dec" => 534, "type" => "word", "access" => "R", "dicription" => "Код состояния системы 1"],
        "code_Sys_2" => ["hex" => "217", "dec" => 535, "type" => "word", "access" => "R", "dicription" => "Код состояния системы 2"],
        "cmd_Start" => ["hex" => "2170", "dec" => 535.0, "type" => "bool", "access" => "R", "dicription" => "Переключения режимов Старт/Стоп"],
        "ub_Is_Tao" => ["hex" => "2173", "dec" => 535.3, "type" => "bool", "access" => "R", "dicription" => "Наличие погодозависимости"],
        "ub_Is_Pwd" => ["hex" => "2174", "dec" => 535.4, "type" => "bool", "access" => "R", "dicription" => "Наличие контроля давления теплоносителя"],
        "ub_Is_AvCheck" => ["hex" => "2175", "dec" => 535.5, "type" => "bool", "access" => "R", "dicription" => "Наличие в системе контроля общекотельных аварий"],
        "lv_Is_AvMode" => ["hex" => "2177", "dec" => 535.7, "type" => "bool", "access" => "R", "dicription" => "Флаг переключения на аварийную стратегию"],
        "mode_Burn" => ["hex" => "219", "dec" => 537, "type" => "word", "access" => "R", "dicription" => "Тип горелки"],
        "code_Burn_1" => ["hex" => "21А", "dec" => 538, "type" => "word", "access" => "R", "dicription" => "Текущее состояние котла № 1"],
        "code_Burn_2" => ["hex" => "21B", "dec" => 539, "type" => "word", "access" => "R", "dicription" => "Текущее состояние котла № 2"],
        "code_Burn_3" => ["hex" => "21С", "dec" => 540, "type" => "word", "access" => "R", "dicription" => "Текущее состояние котла № 3"],
        "code_Burn_4" => ["hex" => "21D", "dec" => 541, "type" => "word", "access" => "R", "dicription" => "Текущее состояние котла № 4"],
        "code_Error" => ["hex" => "220", "dec" => 544, "type" => "word", "access" => "R", "dicription" => "Код состояния аварий 1"],
        "Av_Burn_1" => ["hex" => "2200", "dec" => 544.0, "type" => "bool", "access" => "R", "dicription" => "Авария котла №1"],
        "Av_Burn_2" => ["hex" => "2201", "dec" => 544.1, "type" => "bool", "access" => "R", "dicription" => "Авария котла №2"],
        "Av_Burn_3" => ["hex" => "2202", "dec" => 544.2, "type" => "bool", "access" => "R", "dicription" => "Авария котла №3"],
        "Av_Burn_4" => ["hex" => "2203", "dec" => 544.3, "type" => "bool", "access" => "R", "dicription" => "Авария котла №4"],
        "Av_NoWB" => ["hex" => "2204", "dec" => 544.4, "type" => "bool", "access" => "R", "dicription" => "Нет доступных для работы котлов"],
        "Av_Twd_HAL" => ["hex" => "2205", "dec" => 544.5, "type" => "bool", "access" => "R", "dicription" => "Перегрев (предупреждение)"],
        "Av_Twd_HAL_2" => ["hex" => "2206", "dec" => 544.6, "type" => "bool", "access" => "R", "dicription" => "Перегрев"],
        "vi_Av3Res" => ["hex" => "2208", "dec" => 544.8, "type" => "bool", "access" => "R", "dicription" => "Трехкратный перегрев"],
        "Av_Butt" => ["hex" => "220B", "dec" => 544.11, "type" => "bool", "access" => "R", "dicription" => "Аварийная кнопка"],
        "code_Error" => ["hex" => "221", "dec" => 545, "type" => "word", "access" => "R", "dicription" => "Код состояния аварий 2"],
        "Av_Twd_sens" => ["hex" => "2212", "dec" => 545.2, "type" => "bool", "access" => "R", "dicription" => "Датчик температуры в подающем трубопроводе неисправен"],
        "Av_Pwd_sens" => ["hex" => "2214", "dec" => 545.4, "type" => "bool", "access" => "R", "dicription" => "Датчик давления неисправен"],
        "Av_Pwd_HAL" => ["hex" => "2215", "dec" => 545.5, "type" => "bool", "access" => "R", "dicription" => "Давление теплоносителя велико (аналоговый датчик давления)"],
        "Av_Pwd_LAL" => ["hex" => "2216", "dec" => 545.6, "type" => "bool", "access" => "R", "dicription" => "Давление теплоносителя мало (аналоговый датчик давления)"],
        "Av_Tao_sens" => ["hex" => "2217", "dec" => 545.7, "type" => "bool", "access" => "R", "dicription" => "Неисправен датчик наружного воздуха"],
        "Av_Mod" => ["hex" => "2218", "dec" => 545.8, "type" => "bool", "access" => "R", "dicription" => "Нет связи с модулем расширения ОК аварий"],
        "Av_Fire" => ["hex" => "2219", "dec" => 545.9, "type" => "bool", "access" => "R", "dicription" => "Сработал датчик пожара"],
        "Av_BreakIn" => ["hex" => "221A", "dec" => 545.10, "type" => "bool", "access" => "R", "dicription" => "Сработал датчик взлома"],
        "Av_Pf_HAL" => ["hex" => "221B", "dec" => 545.11, "type" => "bool", "access" => "R", "dicription" => "Давление газа велико"],
        "Av_Pf_LAL" => ["hex" => "221С", "dec" => 545.12, "type" => "bool", "access" => "R", "dicription" => "Давление газа мало"],
        "Av_CO" => ["hex" => "221D", "dec" => 545.13, "type" => "bool", "access" => "R", "dicription" => "Сработал датчик загазованности СО"],
        "Av_CH" => ["hex" => "221E", "dec" => 545.14, "type" => "bool", "access" => "R", "dicription" => "Сработал датчик загазованности СН"],
        "Av_LostConn" => ["hex" => "221F", "dec" => 545.15, "type" => "bool", "access" => "R", "dicription" => "Нет связи с модулем расширения котлов"],
        "ua_Twd" => ["hex" => "222", "dec" => 546, "type" => "word", "access" => "RW", "dicription" => "Уставка температуры теплоносителя"],
        "ua_Twd_DZ" => ["hex" => "223", "dec" => 547, "type" => "real", "access" => "RW", "dicription" => "Зона нечувствительности температуры теплоносителя"],
        "ua_Twd_LWL" => ["hex" => "225", "dec" => 549, "type" => "word", "access" => "RW", "dicription" => "Нижняя рабочая граница температуры теплоносителя"],
        "ua_Twd_HWL" => ["hex" => "226", "dec" => 550, "type" => "word", "access" => "RW", "dicription" => "Верхняя рабочая граница температуры теплоносителя"],
        "lv_Twd_cor" => ["hex" => "227", "dec" => 551, "type" => "word", "access" => "R", "dicription" => "Текущая уставка температуры в подающем трубопроводе"],
        "lv_Twd_LWL" => ["hex" => "228", "dec" => 552, "type" => "word", "access" => "R", "dicription" => "Текущее значение нижней рабочей границы подачи"],
        "lv_Twd_HWL" => ["hex" => "229", "dec" => 553, "type" => "word", "access" => "R", "dicription" => "Текущее значение верхней рабочей границы подачи"],
        "ua_Тwd_HAL" => ["hex" => "22A", "dec" => 554, "type" => "word", "access" => "RW", "dicription" => "Опасно высокая температура теплоносителя"],
        "ua_Twd_HAL_2" => ["hex" => "22B", "dec" => 555, "type" => "word", "access" => "RW", "dicription" => "Аварийно высокая температура теплоносителя"],
        "ut_Integ_Up" => ["hex" => "22C", "dec" => 556, "type" => "word", "access" => "RW", "dicription" => "Интеграл на подключение ступени"],
        "ut_Integ_Dw" => ["hex" => "22D", "dec" => 557, "type" => "word", "access" => "RW", "dicription" => "Интеграл на отключение ступени"],
        "ut_Stab_Up" => ["hex" => "22E", "dec" => 558, "type" => "word", "access" => "RW", "dicription" => "Время стабилизации после подключения ступени"],
        "ut_Stab_Dw" => ["hex" => "22F", "dec" => 559, "type" => "word", "access" => "RW", "dicription" => "Время стабилизации после отключения ступени"],
        "ua_PID_Kp" => ["hex" => "230", "dec" => 560, "type" => "real", "access" => "RW", "dicription" => "ПИД Кп"],
        "ua_PID_Ti" => ["hex" => "232", "dec" => 562, "type" => "word", "access" => "RW", "dicription" => "ПИД Ти"],
        "ua_PID_Td" => ["hex" => "233", "dec" => 563, "type" => "word", "access" => "RW", "dicription" => "ПИД Тд"],
        "ua_Pwd_LAL_2" => ["hex" => "238", "dec" => 568, "type" => "real", "access" => "RW", "dicription" => "Минимальное рабочее (аварийное) давление"],
        "ua_Pwd_HAL_2" => ["hex" => "23A", "dec" => 570, "type" => "real", "access" => "RW", "dicription" => "Максимальное рабочее (аварийное) давление"],
        "ua_Pwr_On" => ["hex" => "23D", "dec" => 573, "type" => "word", "access" => "RW", "dicription" => "Минимальная мощность горения"],
        "ua_Burn_Main" => ["hex" => "23Е", "dec" => 574, "type" => "word", "access" => "RW", "dicription" => "Номер ведущего котла"],
        "vi_Burn_Cng" => ["hex" => "23F", "dec" => 575, "type" => "word", "access" => "R", "dicription" => "Оставшееся время до смены ведущего котла, вминутах"]
    ];
}